### PR TITLE
BUG: maximum call stack size if there is a large number of chords

### PR DESCRIPTION
**Pull request by cheehongsg**
Installed and tested to work for sizeable chord count via "Show Pairs in Circular View".

However, the following dialog popup when we send our experiment interaction data (.bedpe).

IGV JBrowse CircularView Error Dialog

The issue is related to "String.fromCharCode.apply(null, buffer)"
(See [this stackoverflow link](https://stackoverflow.com/questions/22747068/is-there-a-max-number-of-arguments-javascript-functions-can-accept) )

### CODE REVIEW

**Comment by jrobinso** [comment]
Hi @cheehongsg ,  thanks, amazingly I encountered the same bug by coincidence and had already implemented a fix.  Could you pull and try again?  

I haven't announced this yet as I am still working on it, and it need documentation and a tutorial, so kudos for figuring it out.  This will interact with IGV desktop letting you project chords from bedpe,  VCFs with SV info, paired alignments, and long read split alignments.   We have a separate solution of igv.js / igv-webapp that does not need the electron app.   To demo that one see igv.org/app-circview.   Select one of the 3 canned sessions under the "Sessions" menu, and "Show" from the Circular menu.   Then project chords from the various track menus. 

 If I can ask what are your use case(s)?

**Comment by jrobinso** [comment]
BTW my fix was to replace the "apply" call with this

const message = Buffer.from(buffer).toString('utf-8')

**Comment by cheehongsg** [comment]
Hi @jrobinso: Thanks for fix. I prefer your concise change.

I tried it with the cis and trans interaction bedpe files with mixed results.
(Git Repository: [ChIA-PET-Interactions-Visualization](https://github.com/cheehongsg/ChIA-PET-Interactions-Visualization/tree/main/PMID33836152))

Both GSM3553630_HF-3177_chiapet.cis.chiasig.sigf.itx.bedpe.gz and GSM3553630_HF-3177_chiapet.trans.chiasig.itx.ge4.bedpe.gz displayed successfully in the IGV JBrowse CircularView via IGV Desktop.

However, GSM3553630_HF-3177_chiapet.trans.chiasig.itx.ge2.bedpe.gz crashes in the socket data event.

```#
# Fatal error in , line 0
# Fatal JavaScript invalid size error 169220804
#
#
#
#FailureMessage Object: 0x7ffee61ea3c0
 1: 0x10d19e872 node::OnFatalError(char const*, char const*) [/Users/*/circular-view-app-master/dist/mac/IGV JBrowse CircularView.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 2: 0x10f4e0f01 v8::internal::compiler::GetI32WasmCallDescriptor(v8::internal::Zone*, v8::internal::compiler::CallDescriptor const*) [/Users/*/circular-view-app-master/dist/mac/IGV JBrowse CircularView.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 3: 0x10a3ddc35 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArray(int, v8::internal::AllocationType) [/Users/*/circular-view-app-master/dist/mac/IGV JBrowse CircularView.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 4: 0x10a55febf v8::internal::ElementsKindToByteSize(v8::internal::ElementsKind) [/Users/*/circular-view-app-master/dist/mac/IGV JBrowse CircularView.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 5: 0x10a55f2ae v8::internal::ElementsKindToByteSize(v8::internal::ElementsKind) [/Users/*/circular-view-app-master/dist/mac/IGV JBrowse CircularView.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 6: 0x10a714c55 v8::internal::RegExp::CompileForTesting(v8::internal::Isolate*, v8::internal::Zone*, v8::internal::RegExpCompileData*, v8::base::Flags<v8::internal::JSRegExp::Flag, int>, v8::internal::Handle<v8::internal::String>, v8::internal::Handle<v8::internal::String>, bool) [/Users/*/circular-view-app-master/dist/mac/IGV JBrowse CircularView.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
 7: 0x330007d858 
 8: 0x3300214bb0 
 9: 0x33001c4b86 
Trace/BPT trap: 5`
```

Switching back to the earlier patch, renderer.js steps actually completed but crashed out finally in the react-framework for display while V8 was attempting multiple garbage collection.

The good news is the same problematic trans bedpe file displayed successfully in the IGV WebApp circular view (running Chrome).

Given that both IGV-WebApp and this electron app can handle sizeable interaction data (18 MB), it is sufficient for general usage. I propose that we close this with your fix.


Thanks for sharing the app-circview. We use IGV Desktop heavily to explore data and all 3 canned sessions are part of our use cases. Additionally, we explore interactions data via customised IGV (Desktop). Please see "[Exploring ChIA-PET cis-and-trans interactions in IGV WebApp.pdf](https://raw.githubusercontent.com/cheehongsg/ChIA-PET-Interactions-Visualization/main/PMID33836152/Exploring%20ChIA-PET%20cis-and-trans%20interactions%20in%20IGV%20WebApp.pdf)" in the repo for a run through based on IGV-WebApp. You are welcome to use / adapt the session file GBM-HF3177-ChIA-PET-session.json and repo.

By the way, we have moved from the Desktop over to the performant IGV-WebApp since mid Dec. We find it easier to experiment with and extend IGV-WebApp (or igv.js). It is a blessing not having IT to install software for each team member.

**Comment by jrobinso** [comment]
Thank you for that PDF!  This will be very useful.

I'm encouraged that you are finding the webapp useful.

WRT the crashes, I suspect we are encountering memory issues that we won't
be able to overcome with the electron app.  Perhaps the web browser is
allocated more memory or resources than the wrapped chromium app.  In any
event even if we could overcome that I think the resulting figure would be
overwhelming.    To prevent crashes we might set a limit on the # of
interactions in IGV Desktop, or perhaps resort to downsampling the
interactions in IGV desktop before sending to the circ app.

I will be concentrating on getting the circ view ready for beta release, as
well as your other PR, on return from the holidays.

**Comment by jrobinso** [comment]
@cheehongsg This large bedpe file (GSM3553630_HF-3177_chiapet.trans.chiasig.itx.ge2.bedpe.gz) exposed another problem, related to the circ view crash, in IGV itself.   A bedpe file of 1.2 million pairs was not envisioned for that track, so the whole genome view which tries to draw all of them kills the app.   In addition, its not useful to draw 1.2 million of anything.  So on the IGV side I've implemented downsampling for the WG view, the number to downsample to is somewhat arbitrary but 1,000 arcs seems a good number for performance.   Even 10,000 arcs could be drawn but nothing additional is actually seen.   The sampled representation is also sent to circ view.   In addition a maximum of 10,000 arcs is sent to circview from IGV for any individual operation.   Again its pointless to draw more than 10,000 arcs.   Reservoir sampling is used for both cases.    I will implement similar downsampling for WG view in igv.js when I return to that project.

**Comment by cheehongsg** [comment]
> @cheehongsg This large bedpe file (GSM3553630_HF-3177_chiapet.trans.chiasig.itx.ge2.bedpe.gz) exposed another problem, related to the circ view crash, in IGV itself. A bedpe file of 1.2 million pairs was not envisioned for that track, so the whole genome view which tries to draw all of them kills the app. In addition, its not useful to draw 1.2 million of anything. So on the IGV side I've implemented downsampling for the WG view, the number to downsample to is somewhat arbitrary but 1,000 arcs seems a good number for performance. Even 10,000 arcs could be drawn but nothing additional is actually seen. The sampled representation is also sent to circ view. In addition a maximum of 10,000 arcs is sent to circview from IGV for any individual operation. Again its pointless to draw more than 10,000 arcs. Reservoir sampling is used for both cases. I will implement similar downsampling for WG view in igv.js when I return to that project.

@jrobinso  Agree that we will have to impose a limit for software usability and practicality. The reservoir sampling will still allow the key trends to show. It will also remove the hustle of pre-filtering their files for loading. Thanks for taking care of the edge cases.

**Pull request closed without merging**
